# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardGameApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardGameApp
  pod 'SwiftLint'

  target 'CardGameAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardGameAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
